				;-------------------------------------------------------------------------------------
				;
				cBLACK       = $00
				cWHITE       = $01
				cRED         = $02
				cCYAN        = $03
				cVIOLET      = $04
				cGREEN       = $05
				cBLUE        = $06
				cYELLOW      = $07
				cORANGE      = $08
				cBROWN       = $09
				cLIGHTRED    = $0a
				cDARKGREY    = $0b
				cMEDIUMGREY  = $0c
				cLIGHTGREEN  = $0d
				cLIGHTBLUE   = $0e
				cLIGHTERGREY = $0f
				;
				;-------------------------------------------------------------------------------------

